### PR TITLE
fix(test): include path for header files

### LINKED ISSUE #28: Compilation tests are broken
5d4c029d172e2f794b71da294b2024e30fb5881e commit moves all the header files into the [`Templates`](https://github.com/adityaa30/programs/tree/main/Templates) directory breaking the include path for most of the `.cpp` program files.

https://github.com/adityaa30/programs/runs/2650292327

### PR DESCRIPTION
**Pull request by Anoop-kumar900**
ensures all programs are successfully compiling
fixes #28

### CODE REVIEW

File: autocpp.sh [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+set -x
```
Comment (adityaa30) [inline autocpp.sh:2]: Let's remove this debug flag to prevent unnecessary logs while using `autocpp`

File: out [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+'
+++ ./
+test-cpp-compile.sh: line 5: ./: Is a directory
++ CHECK_DIR=
++ '[' 1 == 1 ']'
++ CHECK_DIR=input.txt
++ '[' '!' -d input.txt ']'
++ echo 'Directory '\''input.txt'\'' does not exist.'
+Directory 'input.txt' does not exist.
++ exit 0
```
Comment (adityaa30) [inline out:11]: File not required

File: test-cpp-compile.sh [hunk 3]
```diff
@@ -24,8 +25,10 @@ for path in $CPP_FILES
 do
     # To support programs using pthread we add flag
     # TODO: Use pthread flag only when required
-    g++ $path -o $TEST_PROG_FILE -pthread
-
+    EXTRA_ARGS="-std=c++11"
+    HEADER_PATH="-I$(pwd)/Templates"
+    g++ $EXTRA_ARGS $HEADER_PATH -o $TEST_PROG_FILE $path
```
Comment (adityaa30) [inline test-cpp-compile.sh:30]:
```suggestion
    g++ $EXTRA_ARGS $HEADER_PATH -o $TEST_PROG_FILE $path  -pthread
```

**Review by adityaa30 — CHANGES_REQUESTED** [review]
